# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.CharField(max_length=10)),
                ('year_of_manufacture', models.DateField()),
                ('year_of_purchase', models.DateField()),
                ('total_mileage_in_km', models.IntegerField()),
            ],
        ),
    ]
