# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='reg_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
