# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 10:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0003_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date_of_birth',
            field=models.DateField(default=datetime.date(2000, 2, 12)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='district',
            field=models.CharField(default='kampala', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='first_name',
            field=models.CharField(default='Mutegeki', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='Brian', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='nation',
            field=models.CharField(default='UGANDA', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='permit',
            field=models.CharField(default='123456788/33/', max_length=40, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone_no',
            field=models.CharField(default='+256701544462', max_length=13, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='sex',
            field=models.CharField(default='Male', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='thumb',
            field=models.ImageField(blank=True, default=b'default.png', upload_to=b''),
        ),
    ]
