# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 12:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0004_auto_20180329_1032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='thumb',
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.ImageField(default='drivers/ball.jpeg', upload_to=b'drivers'),
            preserve_default=False,
        ),
    ]
