# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0005_auto_20180329_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='permit',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_no',
            field=models.CharField(max_length=13),
        ),
    ]
