# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-29 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0006_auto_20180329_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='photo',
        ),
        migrations.AddField(
            model_name='driver',
            name='thumb',
            field=models.ImageField(blank=True, default=b'default.png', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='permit',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone_no',
            field=models.CharField(max_length=13, unique=True),
        ),
    ]
