# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 10:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0007_auto_20180329_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.CharField(max_length=15)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='driver',
            name='thumb',
        ),
    ]
