# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-26 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0010_service_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='air',
            field=models.CharField(default='yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='battery',
            field=models.CharField(default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='breaks',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='diff',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='engine',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='flush',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='fuel',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='gear',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='greasing',
            field=models.CharField(default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='nexts',
            field=models.CharField(default='11245', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='oil',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='raditor',
            field=models.CharField(default='No', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='spark',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='steering',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='wind',
            field=models.CharField(default='Yes', max_length=10),
            preserve_default=False,
        ),
    ]
