# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 11:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0012_car_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='service',
        ),
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycar.Car'),
            preserve_default=False,
        ),
    ]
