# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-13 12:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycar', '0014_remove_service_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mycar.Car'),
            preserve_default=False,
        ),
    ]
